Updated Vehicle Section
evcc-io/config pull request #71
Opened 2021-09-17 15:40 UTC by int5749

Compared and incorporated changes from Readme

2021-09-17 15:50 UTC, andig requested changes

2021-09-17 15:50 UTC, andig commented on yaml/vehicles/audi.yaml
> +name: Audi (eTron, Q55, etc)
Wozu die Änderung? Es gibt noch jede Menge Hybride...

2021-09-17 15:50 UTC, andig commented on yaml/vehicles/bmw.yaml
> +name: BMW and Mini (i3, Cooper SE)
das Verwirrt. Laut README ist mini `mini`

2021-09-17 15:50 UTC, andig commented on yaml/vehicles/enyaq.yaml
> +type: vw
FALSCH!!!

2021-09-17 15:50 UTC, andig commented on yaml/vehicles/ovms.yaml
> +name: OVMS (f.i. Twizzy, Smart ED)
wozu die Änderung?

2021-09-17 15:52 UTC, int5749 commented on yaml/vehicles/audi.yaml
> +name: Audi (eTron, Q55, etc)
Stand so in der Readme, nur harmonisiert

2021-09-17 15:55 UTC, andig commented on yaml/vehicles/audi.yaml
> +name: Audi (eTron, Q55, etc)
Dann lassen wir das. Kein Mehrwert

2021-09-17 15:58 UTC, premultiply commented on yaml/vehicles/audi.yaml
> +name: Audi (eTron, Q55, etc)
Am besten die Modelle überall ganz streichen. Das sind inzwischen so viele das kann man ohnehin nicht mehr sinnvoll pflegen.

2021-09-17 16:53 UTC, andig commented on yaml/vehicles/audi.yaml
> +name: Audi (eTron, Q55, etc)
Außer wo wir differenzieren müssen: ID, Enyaq wäre ich dabei

2021-09-17 17:30 UTC, int5749 commented on yaml/vehicles/audi.yaml
> +name: Audi (eTron, Q55, etc)
OK, überabeite dies. In der Readme sollen die Modelle dann aber enthalten bleiben?

2021-09-17 17:48 UTC, andig commented on yaml/vehicles/audi.yaml
> +name: Audi (eTron, Q55, etc)
yep, tut erstmal nicht weh

2021-09-17 17:49 UTC, andig commented
LGTM! @premultiply ?

2021-09-17 17:51 UTC, int5749 commented
Bitte noch VW und ID prüfen, sind die nicht doppelt? Oder soll die so bleiben? Läuft beides als VW?

2021-09-19 17:30 UTC, int5749 commented
@premultiply War Dein 👍 als Zustimmung gemeint? Nach diesem Update würde ich dann das (richtige) Wiki bereinigen.

2021-09-19 17:54 UTC, premultiply commented
Ja

2021-09-19 17:58 UTC, merged